PATH=${HOME}/.asdf/shims:${HOME}/.local/bin:${HOME}/.local/scripts:${HOME}/.cargo/bin:${HOME}/go/bin:${PATH}

# Stem darkening for macOS-like font weight at small sizes
FREETYPE_PROPERTIES="cff:no-stem-darkening=0 cff:darkening-parameters=500,450,1000,400,1667,300,2333,0 autofitter:no-stem-darkening=0 autofitter:darkening-parameters=500,450,1000,400,1667,300,2333,0"
