#!/bin/bash

bluetoothctl power on
id=$(bluetoothctl devices Paired | rg JBL | awk '{ print $2 }')
[[ -z "$id" ]] && id=$(bluetoothctl devices | rg JBL | awk '{ print $2 }')

if bluetoothctl info "$id" | rg -q 'Connected: yes'; then
  bluetoothctl disconnect "$id"
else
  bluetoothctl connect "$id"
fi
