#!/usr/bin/env bash

STATE_FILE="$HOME/.cache/sway-server-mode"

if [ -f "$STATE_FILE" ]; then
    rm "$STATE_FILE"
    notify-send "Server Mode OFF" "Closing lid suspends the machine"
else
    touch "$STATE_FILE"
    notify-send "Server Mode ON" "Lid close turns screen off, lid open turns it back on"
fi

# Signal waybar to update (signal 4 = SIGRTMIN+4)
pkill -RTMIN+4 waybar
