#!/usr/bin/env bash

current_brightness=$(
  xrandr --verbose | rg " connected" -A5 | rg "Brightness" | awk '{ print $2 }'
)
current_monitor=$(
  xrandr | rg " connected" | awk '{ print $1 }'
)

# +0.05 for example
step="$@"
[[ -z $step ]] && echo $current_brightness

new_brightness=$(echo $current_brightness $step | bc)

if (( $(echo "$new_brightness > 1" | bc -l) )); then
    new_brightness=1
elif (( $(echo "$new_brightness < 0.25" | bc -l) )); then
    new_brightness=0.25
fi

xrandr --output $current_monitor --brightness $new_brightness
