#!/usr/bin/env bash

start() {
    SLOP=$(slop -f "%x %y %w %h %g %i") || exit 1
    read -r X Y W H G ID <<< $SLOP
    REGION="-s ${W}x${H} -i ${DISPLAY}+${X},${Y}"

    audio=false
    output_gif=true
    output=~/Videos/rec-$(date +%Y%m%d-%H%M)
    [[ "$output_gif" == "true" ]] && echo "$output" > /tmp/recgif

    # ### https://kerkour.com/video-formats-codecs-containers
    # ffmpeg -i [VIDEO_SOURCE] -map_metadata -1 -b:v 0 -movflags +faststart \
    #     -c:v libsvtav1 -preset 6 -crf 30 -c:a libopus -b:a 128k \
    #     [VIDEO_DESTINATION.mkv]

    opts=(-c:v h264)
    [[ "$audio" == "true" ]] && opts+=(-f pulse -i default)
    # opts+=(-map_metadata -1 -b:v 0 -movflags +faststart -c:v libsvtav1 -preset 6 -crf 30 -c:a libopus -b:a 128k)

    ffmpeg -f x11grab $REGION "${opts[@]}" "$output.mp4" &
    echo $! > /tmp/recpid

    # width and height of the window, x and y are where window start on the monitor
    # so screenkey should be relative to the width and height plus x and y
    screenkey --mouse -p fixed -g "$(($W * 23/100))x$(($H * 8/100))+$(($X + $W * 3/4))+$(($Y + $H * 9/10))" --opacity 0.4 &
    echo $! > /tmp/recscreenkeypid

    notify-send -t 1000 "Recording started"
}

end() {
    recpid=$(cat /tmp/recpid)
    kill -15 "$recpid" $(cat /tmp/recscreenkeypid)
    tail --pid="$recpid" -f /dev/null  # wait for ffmpeg to finish writing
    rm -f /tmp/recpid /tmp/recscreenkeypid
    notify-send -t 1000 "Recording stopped"

    if [[ -f /tmp/recgif ]]; then
        output=$(cat /tmp/recgif)
        rm -f /tmp/recgif
        notify-send -t 1000 "Converting to gif..."

        vf_opts=()
        vf_opts+=(fps=10)               # reduce framerate (default ~30)
        # vf_opts+=(scale=iw/2:-1)        # halve resolution

        gen_opts=()
        gen_opts+=(max_colors=128)      # reduce palette (default 256)

        use_opts=()
        use_opts+=(dither=bayer)        # fast grid dithering to simulate missing colors
        # use_opts+=(diff_mode=rectangle)  # only encode changed regions (no improvement in tests)

        vf=$(IFS=,; echo "${vf_opts[*]}")
        gen=$(IFS=:; echo "${gen_opts[*]}")
        use=$(IFS=:; echo "${use_opts[*]}")

        if command -v gifski &>/dev/null; then
            ffmpeg -loglevel error -i "$output.mp4" -vf fps=10 -f yuv4mpegpipe - | \
                gifski --fps 10 --quality 80 --output "$output.gif" -
        else
            ffmpeg -i "$output.mp4" -filter_complex \
                "[0:v]${vf},palettegen=${gen}[pal];[0:v]${vf}[vid];[vid][pal]paletteuse=${use}" \
                "$output.gif"
        fi && notify-send -t 1000 "Gif ready"

        printf '%s\n' "$output.mp4" "$output.gif" | dragon --and-exit --stdin
    else
        ls ~/Videos/rec-*.mp4 | tail -1 | dragon --and-exit --stdin
    fi
}

if [[ -f /tmp/recpid && -f /tmp/recscreenkeypid ]]; then
    end
else
    start
fi
